[workspace]
authors = []
channels = ["conda-forge"]
name = "docker-image"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.6,<5"
jupyter-resource-usage = ">=1.2.0,<2"
jupyterlab_code_formatter = ">=3.0.2,<4"
black = ">=25.1.0,<26"
isort = ">=6.0.1,<7"
ruff = ">=0.12.10,<0.13"
dask-labextension = ">=7.0.0,<8"
dask = ">=2025.7.0,<2026"
distributed = ">=2025.7.0,<2026"
xarray = ">=2025.8.0,<2026"
xdggs = ">=0.2.1,<0.3"
healpix-geo = ">=0.0.6,<0.0.7"
jedi-language-server = ">=0.45.1,<0.46"
jupyterlab-myst = ">=2.4.2,<3"
zarr = ">=3.1.2,<4"
netcdf4 = ">=1.7.2,<2"
scipy = ">=1.16.1,<2"
h5netcdf = ">=1.6.4,<2"
rioxarray = ">=0.19.0,<0.20"
pooch = ">=1.8.2,<2"
scikit-learn = ">=1.7.1,<2"
jupyterlab-notifications = ">=0.5.0,<0.6"
jupyterlab_rise = ">=0.43.1,<0.44"
jupyter-fs = ">=1.1.0,<2"
jupyterlab-mathjax3 = ">=4.3.0,<5"
jupyterlab-s3-browser = ">=0.12.0,<0.13"
jupyterlab-search-replace = ">=1.1.0,<2"
sidecar = ">=0.7.0,<0.8"
virtualizarr = ">=2.1.1,<3"
kerchunk = ">=0.2.9,<0.3"
fastparquet = ">=2024.11.0,<2025"
xarray-eopf = ">=0.0.1,<0.0.2"
shapely = ">=2.1.1,<3"
geopandas = ">=1.1.1,<2"
xvec = ">=0.5.1,<0.6"
cf-xarray = ">=0.10.7,<0.11"
pint-xarray = ">=0.5.1,<0.6"
hvplot = ">=0.12.0,<0.13"
matplotlib-base = ">=3.10.5,<4"
cartopy = ">=0.25.0,<0.26"
flox = ">=0.10.6,<0.11"
numbagg = ">=0.9.0,<0.10"
opt_einsum = ">=3.4.0,<4"
cftime = ">=1.6.4,<2"
sparse = ">=0.17.0,<0.18"
nc-time-axis = ">=1.4.1,<2"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.3.2,<3"
python = "3.13.*"
pyvista-xarray = ">=0.1.7,<0.2"
s3fs = ">=2025.7.0,<2026"
obstore = ">=0.8.1,<0.9"
